---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[chef_apache_hardening::default]
      - recipe[apache2::mod_ssl]
      - recipe[chef_apache_hardening::config_ssl]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: 